[base]
package = ocean
env_name = puffer_ctf
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 128
num_workers = 16
batch_size = 128
zero_copy = False
backend = Multiprocessing

[env]
num_envs = 128

[train]
device = cpu
env_batch_size = 32
batch_size = auto
bptt_horizon = 64
minibatch_size = 1024
total_timesteps = 15_000_000
use_rnn = true
learning_rate = 0.005
gamma = 0.995
ent_coef = 0.013449906174558369
# Reward Shaping - "No Fear" setup
use_reward_wrapper = true
reward_move_to_enemy = 0.01
reward_move_to_own = 0.05
reward_flag_hold = 0.01
# Zero out tagging penalty to encourage flag capture attempts
penalty_tagged = 0.0
penalty_step = -0.001
penalty_wall = -0.1
