[base]
package = ocean
env_name = puffer_ctf
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 128
num_workers = 16
batch_size = 32
zero_copy = False
backend = Multiprocessing

[env]
num_envs = 128

[train]
device = cpu
env_batch_size = 32
batch_size = auto
total_timesteps = 2_000_000
use_rnn = false
learning_rate = 0.005
gamma = 0.99
# Aggressive Reward Shaping Overrides
use_reward_wrapper = true
reward_move_to_enemy = 5.0
reward_move_to_own = 10.0
reward_flag_hold = 1.0
penalty_tagged = -0.1
penalty_step = -0.01
